import 'package:cloud_firestore/cloud_firestore.dart';

class SeedDataService {
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  Future<void> uploadDesignProjects() async {
    final List<Map<String, dynamic>> projects = [
      {
        'id': 'warm_minimal_bedroom',
        'title': 'Warm Minimal Bedroom',
        'roomType': 'Bedroom',
        'mood': 'Relaxing',
        'style': 'Minimal',
        'budgetLevel': 'Medium',
        'timeContext': 'Night',
        'lightingCondition': 'Dark',
        'spaceProblem': 'Too crowded',
        'imageUrl': 'assets/images/warm_minimal_bedroom.jpg',
        'challenge': 'The original room felt dark, crowded, and visually stressful.',
        'solution': 'Warm indirect lighting, light textiles, and hidden storage were used to create a calmer sleeping space.',
        'valueAdded': 'Improved comfort, visual openness, and emotional relaxation.',
        'beforeDescription': 'Dark corners, visible clutter, and heavy furniture made the bedroom feel stressful.',
        'afterDescription': 'The redesigned bedroom feels warmer, brighter, and more peaceful for nighttime rest.',
        'skills': ['Lighting Design', 'Space Planning', 'Storage Optimization'],
        'materials': ['Wood', 'Linen', 'Warm LED'],
        'colorPalette': ['Cream', 'Warm Brown', 'Soft Beige'],
        'relatedServices': ['Lighting Design', 'Space Planning', 'Storage Optimization'],
        'featured': true,
      },
      {
        'id': 'natural_living_room',
        'title': 'Natural Living Room',
        'roomType': 'Living Room',
        'mood': 'Cozy',
        'style': 'Natural',
        'budgetLevel': 'Medium',
        'timeContext': 'Evening',
        'lightingCondition': 'Medium',
        'spaceProblem': 'Not stylish',
        'imageUrl': 'assets/images/natural_living_room.jpg',
        'challenge': 'The living room lacked warmth and a clear visual focus.',
        'solution': 'Natural textures, soft seating, plants, and layered lighting were arranged around a calm social center.',
        'valueAdded': 'Made the room warmer, more welcoming, and more connected to daily living.',
        'beforeDescription': 'The room had furniture but no clear atmosphere or design identity.',
        'afterDescription': 'The space now feels cohesive, relaxed, and suitable for evening social use.',
        'skills': ['Color Coordination', 'Furniture Arrangement', 'Mood Creation'],
        'materials': ['Wood', 'Cotton', 'Indoor Plants'],
        'colorPalette': ['Sage', 'Cream', 'Natural Wood'],
        'relatedServices': ['Color Consultation', 'Space Planning'],
        'featured': true,
      },
      {
        'id': 'productive_home_office',
        'title': 'Productive Home Office',
        'roomType': 'Office',
        'mood': 'Productive',
        'style': 'Modern',
        'budgetLevel': 'Low',
        'timeContext': 'Morning',
        'lightingCondition': 'Bright',
        'spaceProblem': 'Distracting',
        'imageUrl': 'assets/images/productive_home_office.jpg',
        'challenge': 'The client needed a focused workspace inside a small apartment.',
        'solution': 'A compact desk zone, task lighting, and clean storage separated work from rest.',
        'valueAdded': 'Improved focus, organization, and daily work comfort without needing a separate room.',
        'beforeDescription': 'Work items were mixed with living-room furniture, causing distraction.',
        'afterDescription': 'The new layout creates a clear work zone with better lighting and organization.',
        'skills': ['Space Planning', 'Ergonomic Layout', 'Natural Lighting'],
        'materials': ['Light Wood', 'White Desk', 'Task Lamp'],
        'colorPalette': ['White', 'Light Wood', 'Soft Blue'],
        'relatedServices': ['Space Planning', 'Lighting Design'],
        'featured': true,
      },
      {
        'id': 'luxury_apartment_lounge',
        'title': 'Luxury Apartment Lounge',
        'roomType': 'Living Room',
        'mood': 'Luxury',
        'style': 'Luxury',
        'budgetLevel': 'High',
        'timeContext': 'Evening',
        'lightingCondition': 'Medium',
        'spaceProblem': 'Not stylish',
        'imageUrl': 'assets/images/luxury_apartment_lounge.jpg',
        'challenge': 'The apartment lounge needed a stronger premium identity for entertaining guests.',
        'solution': 'Rich textures, darker accents, metallic details, and sculptural lighting created a refined lounge atmosphere.',
        'valueAdded': 'Created a high-end visual identity while preserving comfort and social usability.',
        'beforeDescription': 'The lounge looked plain and did not reflect a premium lifestyle.',
        'afterDescription': 'The lounge now feels elegant, atmospheric, and suitable for hosting.',
        'skills': ['Material Selection', 'Luxury Styling', 'Lighting Design'],
        'materials': ['Marble', 'Velvet', 'Brass'],
        'colorPalette': ['Charcoal', 'Gold', 'Deep Brown'],
        'relatedServices': ['Luxury Styling', 'Lighting Design'],
        'featured': true,
      },
      {
        'id': 'scandinavian_kitchen',
        'title': 'Bright Scandinavian Kitchen',
        'roomType': 'Kitchen',
        'mood': 'Fresh',
        'style': 'Scandinavian',
        'budgetLevel': 'Medium',
        'timeContext': 'Morning',
        'lightingCondition': 'Bright',
        'spaceProblem': 'Not functional',
        'imageUrl': 'assets/images/scandinavian_kitchen.jpg',
        'challenge': 'The kitchen felt narrow and did not support a bright morning routine.',
        'solution': 'White cabinetry, light wood surfaces, and open shelving made the kitchen cleaner and brighter.',
        'valueAdded': 'Improved morning usability, visual brightness, and storage clarity.',
        'beforeDescription': 'The kitchen had limited storage visibility and felt visually heavy.',
        'afterDescription': 'The kitchen now feels open, fresh, and easier to use in the morning.',
        'skills': ['Kitchen Planning', 'Natural Lighting', 'Material Coordination'],
        'materials': ['White Tile', 'Oak Wood', 'Matte Cabinetry'],
        'colorPalette': ['White', 'Oak', 'Light Grey'],
        'relatedServices': ['Space Planning', 'Storage Optimization'],
        'featured': false,
      },
      {
        'id': 'cozy_cafe_corner',
        'title': 'Cozy Café Corner',
        'roomType': 'Café',
        'mood': 'Cozy',
        'style': 'Vintage',
        'budgetLevel': 'Medium',
        'timeContext': 'Afternoon',
        'lightingCondition': 'Medium',
        'spaceProblem': 'Not stylish',
        'imageUrl': 'assets/images/cozy_cafe_corner.jpg',
        'challenge': 'The café needed a memorable seating corner that encouraged customers to stay longer.',
        'solution': 'Soft seating, warm pendant lights, wood furniture, and wall art created a comfortable brand atmosphere.',
        'valueAdded': 'Strengthened customer experience and improved the café’s visual identity.',
        'beforeDescription': 'The seating area looked generic and did not support brand memory.',
        'afterDescription': 'The corner became a warmer, more photogenic and comfortable customer zone.',
        'skills': ['Brand Atmosphere', 'Furniture Selection', 'Customer Experience'],
        'materials': ['Wood', 'Leather', 'Pendant Lighting'],
        'colorPalette': ['Coffee Brown', 'Cream', 'Amber'],
        'relatedServices': ['Lighting Design', 'Color Consultation'],
        'featured': true,
      },
      {
        'id': 'compact_studio_apartment',
        'title': 'Compact Studio Apartment',
        'roomType': 'Apartment',
        'mood': 'Functional',
        'style': 'Modern',
        'budgetLevel': 'Low',
        'timeContext': 'Any',
        'lightingCondition': 'Medium',
        'spaceProblem': 'Too small',
        'imageUrl': 'assets/images/compact_studio_apartment.jpg',
        'challenge': 'The studio needed to support sleeping, working, and relaxing in one small space.',
        'solution': 'Multifunctional furniture, zoning rugs, and vertical storage separated the space without building walls.',
        'valueAdded': 'Made the apartment feel larger, more organized, and easier to live in.',
        'beforeDescription': 'All activities overlapped in one area, making the apartment feel cramped.',
        'afterDescription': 'The space now has clearer zones for rest, work, and daily living.',
        'skills': ['Small-Space Planning', 'Multifunctional Layout', 'Storage Design'],
        'materials': ['Modular Furniture', 'Rug', 'Wall Shelves'],
        'colorPalette': ['White', 'Grey', 'Light Wood'],
        'relatedServices': ['Space Planning', 'Storage Optimization'],
        'featured': true,
      },
      {
        'id': 'calm_reading_nook',
        'title': 'Calm Reading Nook',
        'roomType': 'Study',
        'mood': 'Relaxing',
        'style': 'Natural',
        'budgetLevel': 'Low',
        'timeContext': 'Night',
        'lightingCondition': 'Dark',
        'spaceProblem': 'Too dark',
        'imageUrl': 'assets/images/calm_reading_nook.jpg',
        'challenge': 'The client wanted a small quiet corner for reading and evening rest.',
        'solution': 'A comfortable chair, warm floor lamp, side table, and textured rug formed a compact relaxation zone.',
        'valueAdded': 'Created a personal retreat without requiring major renovation.',
        'beforeDescription': 'The corner was unused because it was too dark and lacked purpose.',
        'afterDescription': 'The corner became a focused, warm, and restful reading space.',
        'skills': ['Mood Creation', 'Lighting Design', 'Furniture Placement'],
        'materials': ['Wool Rug', 'Fabric Chair', 'Warm Lamp'],
        'colorPalette': ['Cream', 'Taupe', 'Warm Yellow'],
        'relatedServices': ['Lighting Design', 'Furniture Selection'],
        'featured': false,
      },
      {
        'id': 'spa_inspired_bathroom',
        'title': 'Spa-Inspired Bathroom',
        'roomType': 'Bathroom',
        'mood': 'Relaxing',
        'style': 'Natural',
        'budgetLevel': 'High',
        'timeContext': 'Night',
        'lightingCondition': 'Dark',
        'spaceProblem': 'Not stylish',
        'imageUrl': 'assets/images/spa_inspired_bathroom.jpg',
        'challenge': 'The bathroom felt cold and purely functional instead of calming.',
        'solution': 'Stone textures, warm lighting, hidden storage, and neutral tones created a spa-like atmosphere.',
        'valueAdded': 'Turned a basic bathroom into a relaxing self-care space.',
        'beforeDescription': 'The bathroom was clean but emotionally cold and visually plain.',
        'afterDescription': 'The bathroom became warmer, softer, and more suitable for evening relaxation.',
        'skills': ['Material Selection', 'Lighting Design', 'Storage Planning'],
        'materials': ['Stone Tile', 'Warm LED', 'Wood Vanity'],
        'colorPalette': ['Stone Grey', 'Warm Beige', 'Wood'],
        'relatedServices': ['Lighting Design', 'Storage Optimization', 'Luxury Styling'],
        'featured': false,
      },
      {
        'id': 'quiet_student_study',
        'title': 'Quiet Student Study',
        'roomType': 'Study',
        'mood': 'Productive',
        'style': 'Minimal',
        'budgetLevel': 'Low',
        'timeContext': 'Afternoon',
        'lightingCondition': 'Bright',
        'spaceProblem': 'Distracting',
        'imageUrl': 'assets/images/quiet_student_study.jpg',
        'challenge': 'The study area needed to reduce distractions and support long study sessions.',
        'solution': 'A clean desk layout, simple storage, neutral colors, and task lighting created a focused environment.',
        'valueAdded': 'Improved concentration and made the small study area easier to maintain.',
        'beforeDescription': 'The desk was cluttered, poorly lit, and visually distracting.',
        'afterDescription': 'The new study area feels clean, focused, and suitable for long work sessions.',
        'skills': ['Ergonomic Layout', 'Visual Simplification', 'Task Lighting'],
        'materials': ['Desk Lamp', 'White Desk', 'Wall Shelf'],
        'colorPalette': ['White', 'Light Grey', 'Pale Wood'],
        'relatedServices': ['Space Planning', 'Lighting Design', 'Storage Optimization'],
        'featured': false,
      },
    ];

    for (final project in projects) {
      final String id = project['id'];
      final Map<String, dynamic> data = Map<String, dynamic>.from(project);
      data.remove('id');

      await _db.collection('designProjects').doc(id).set(data);
    }
  }
}