// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9kPIMCV0S_EE2gQ1ud92v3buIW5OoUQY',
    appId: '1:201992041662:web:dd84a832129ab47e001aef',
    messagingSenderId: '201992041662',
    projectId: 'challenge2-b840d',
    authDomain: 'challenge2-b840d.firebaseapp.com',
    storageBucket: 'challenge2-b840d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ1k5zegXuvZYq5DDgo2cRbJkZ0-uGiDo',
    appId: '1:201992041662:android:2ea1ac88ac9a4f76001aef',
    messagingSenderId: '201992041662',
    projectId: 'challenge2-b840d',
    storageBucket: 'challenge2-b840d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWlZwyR9psXpeSYoKemGQoTf_mm2wfySo',
    appId: '1:201992041662:ios:7ec53de65ff2bdb4001aef',
    messagingSenderId: '201992041662',
    projectId: 'challenge2-b840d',
    storageBucket: 'challenge2-b840d.firebasestorage.app',
    iosBundleId: 'com.example.challenge2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9kPIMCV0S_EE2gQ1ud92v3buIW5OoUQY',
    appId: '1:201992041662:web:f20e14fcee941d8d001aef',
    messagingSenderId: '201992041662',
    projectId: 'challenge2-b840d',
    authDomain: 'challenge2-b840d.firebaseapp.com',
    storageBucket: 'challenge2-b840d.firebasestorage.app',
  );
}
